"""
Reset home/ to an empty scaffold matching guides/SCAFFOLDING.md.

Default: nuke everything under home/ except PAI.md, then re-scaffold.
--messages: only clear message threads + the iMessage inbound cursor
            (so the next boot starts fresh from current chat.db MAX(ROWID)
            instead of replaying the whole backlog).
"""

import argparse
import shutil
from pathlib import Path

from boot.paths import HOME_DIR

SCAFFOLD_DIRS = [
    "communication/messages",
    "memory/myself",
    "memory/people",
    "memory/topics",
    "memory/journal",
    "memory/skills",
    "proc",
    "events",
    "tmp",
    "workspace",
]


def reset_all() -> None:
    if not HOME_DIR.exists():
        print("home/ does not exist, creating fresh scaffold.")
    else:
        for child in HOME_DIR.iterdir():
            if child.name == "PAI.md":
                continue
            if child.is_dir():
                shutil.rmtree(child)
            else:
                child.unlink()
        print("Cleared home/.")

    for d in SCAFFOLD_DIRS:
        (HOME_DIR / d).mkdir(parents=True, exist_ok=True)

    print("Scaffold restored.")


def _is_stub_person(about_path: Path) -> bool:
    """True if this is an untouched auto-generated person stub (name matches
    slug, empty relationship + entry). Preserves hand-edited bios."""
    try:
        import yaml
        with about_path.open() as f:
            data = yaml.safe_load(f) or {}
    except Exception:
        return False
    slug = about_path.parent.name
    if data.get("name") != slug:
        return False
    if (data.get("relationship") or "").strip():
        return False
    if (data.get("entry") or "").strip():
        return False
    return True


def reset_messages() -> None:
    msgs = HOME_DIR / "communication" / "messages"
    events = HOME_DIR / "events"
    cursor = HOME_DIR / "tmp" / "drivers" / "imessage_in" / "cursor.yaml"
    people = HOME_DIR / "memory" / "people"

    if msgs.exists():
        for child in msgs.iterdir():
            if child.is_symlink() or child.is_file():
                child.unlink()
            else:
                shutil.rmtree(child)
        print(f"Cleared {msgs.relative_to(HOME_DIR)}/")
    msgs.mkdir(parents=True, exist_ok=True)

    if events.exists():
        for child in events.iterdir():
            if child.is_file():
                child.unlink()
        print(f"Cleared {events.relative_to(HOME_DIR)}/")

    if cursor.exists():
        cursor.unlink()
        print(f"Deleted {cursor.relative_to(HOME_DIR)} — next boot re-bootstraps from MAX(ROWID).")

    # Sweep autogenerated phone/email-slugged people stubs (empty bio,
    # name == slug). Keeps hand-edited entries like Emily even if they
    # happen to live under an h-slug.
    if people.exists():
        removed = []
        for child in people.iterdir():
            if not child.is_dir():
                continue
            about = child / "about.yaml"
            if about.exists() and _is_stub_person(about):
                shutil.rmtree(child)
                removed.append(child.name)
        if removed:
            print(f"Removed {len(removed)} untouched people stub(s): {', '.join(removed)}")

    print("Messages reset. Restart the kernel.")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--messages",
        action="store_true",
        help="Only clear message threads + iMessage cursor + pending events.",
    )
    args = parser.parse_args()
    if args.messages:
        reset_messages()
    else:
        reset_all()


if __name__ == "__main__":
    main()
