name: email
kind: driver
version: 0.1.0
description: Email driver namespace; ships macmail subdriver
deps:
  - tailer
  - draft-email
home:
  links:
    - link: mail
      target: var/spool/communication/email
    - link: communication/email
      target: var/spool/communication/email
    - link: drafts
      target: var/spool/communication/email/drafts
