#!/usr/bin/env python3
"""Export cookies from a macOS Chrome profile into Netscape cookies.txt.

Chrome locks its `Cookies` SQLite file while running, so we copy it to a
temp path before reading. AES-128-CBC with a Keychain-derived key.
Output format is what browser-use's `cookies_file=` expects.

macOS only in v1.
"""
from __future__ import annotations

import argparse
import os
import shutil
import sqlite3
import subprocess
import sys
import tempfile
from pathlib import Path

from Crypto.Cipher import AES
from Crypto.Protocol.KDF import PBKDF2

PAI_ROOT = Path(os.environ.get("PAI_ROOT", str(Path.home() / ".pai")))
COOKIES_DIR = PAI_ROOT / "var" / "lib" / "browse" / "cookies"
CHROME_DIR = Path.home() / "Library" / "Application Support" / "Google" / "Chrome"

SALT = b"saltysalt"
ITERATIONS = 1003
IV = b" " * 16
KEY_LEN = 16


def _keychain_password() -> bytes:
    out = subprocess.run(
        ["security", "find-generic-password", "-wa", "Chrome"],
        check=True, capture_output=True, text=True,
    )
    return out.stdout.strip().encode("utf-8")


def _derive_key() -> bytes:
    return PBKDF2(_keychain_password(), SALT, dkLen=KEY_LEN, count=ITERATIONS)


def _decrypt(blob: bytes, key: bytes) -> str:
    if not blob:
        return ""
    if blob[:3] != b"v10":
        # Unencrypted (rare on modern Chrome) — return as utf-8.
        try:
            return blob.decode("utf-8")
        except UnicodeDecodeError:
            return ""
    cipher = AES.new(key, AES.MODE_CBC, IV)
    decrypted = cipher.decrypt(blob[3:])
    pad = decrypted[-1]
    if 1 <= pad <= 16:
        decrypted = decrypted[:-pad]
    return decrypted.decode("utf-8", errors="replace")


def _read_cookies(db_path: Path):
    with tempfile.TemporaryDirectory() as tmp:
        copy = Path(tmp) / "Cookies"
        shutil.copy2(db_path, copy)
        conn = sqlite3.connect(str(copy))
        try:
            cur = conn.execute(
                "SELECT host_key, path, is_secure, expires_utc, name, "
                "value, encrypted_value, is_httponly "
                "FROM cookies"
            )
            yield from cur.fetchall()
        finally:
            conn.close()


def _to_netscape(rows, key: bytes) -> str:
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by pai/subagents/browse/chrome_cookies_import.py",
        "",
    ]
    for host, path, is_secure, expires_utc, name, value, encrypted, is_httponly in rows:
        if not value and encrypted:
            value = _decrypt(bytes(encrypted), key)
        if not value:
            continue
        # Chrome uses microseconds since 1601-01-01; Netscape wants Unix seconds.
        expires = max(0, expires_utc // 1_000_000 - 11_644_473_600) if expires_utc else 0
        domain = host
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        prefix = "#HttpOnly_" if is_httponly else ""
        lines.append(
            f"{prefix}{domain}\t{include_subdomains}\t{path}\t"
            f"{'TRUE' if is_secure else 'FALSE'}\t{expires}\t{name}\t{value}"
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--profile", default="Default",
                    help="Chrome profile directory name (e.g. 'Default', 'Profile 1')")
    args = ap.parse_args()

    if sys.platform != "darwin":
        sys.exit("chrome_cookies_import: macOS only in v1")

    profile_dir = CHROME_DIR / args.profile
    db = profile_dir / "Cookies"
    if not db.is_file():
        # Newer Chrome stores cookies under Network/.
        alt = profile_dir / "Network" / "Cookies"
        if alt.is_file():
            db = alt
        else:
            sys.exit(f"chrome_cookies_import: no Cookies db in {profile_dir}")

    key = _derive_key()
    rows = list(_read_cookies(db))
    out = _to_netscape(rows, key)

    COOKIES_DIR.mkdir(parents=True, exist_ok=True)
    target = COOKIES_DIR / f"{args.profile}.txt"
    target.write_text(out)
    print(f"wrote {len(rows)} cookies to {target}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
